// Api to save the new receipt is /Erp.BO.ReceiptSvc/Receipts with POST

export const receiptWithDtls = {
  Company: 'WOOD01',
  VendorNum: 1,
  PurPoint: '',
  PackSlip: 'packslip1',
  ReceiptDate: '2024-05-21T10:35:32.617Z',
  SaveForInvoicing: true,
  Invoiced: true,
  RcvDtls: [
    {
      Company: 'WOOD01',
      VendorNum: 1,
      PurPoint: '',
      PackSlip: 'packslip2',
      PackLine: 1,
      ReceiptDate: '2024-05-13',
      Invoiced: false,
      PONum: 26883,
      AutoReceipt: false,
      POType: 'Std',
      Received: true,
      ReceivedTo: 'PUR-STK',
      ReceivedComplete: true,
      ArrivedDate: '2024-05-13',
      VendorQty: '10',
      POLine: 1,
      PORelNum: 1,
      PartNum: 'B61',
      BinNum: 'RCV',
      EnableBin: false,
      WareHouseCode: 'Main',
      JobSeqType: '',
      JobSeq: 0,
      OurQty: '1',
      InputOurQty: '1',
      IUM: 'EA',
      RowMod: 'A',
    },
  ],
};

// Api to save the new receipt is /Erp.BO.ReceiptSvc/Receipts with POST
export const receiptWithoutPackline = {
  Company: 'WOOD01',
  VendorNum: 1,
  PurPoint: '',
  PackSlip: 'qwerty',
  ReceiptDate: '2024-05-21T10:35:32.617Z',
  SaveForInvoicing: true,
  Invoiced: true,
  RowMod: 'A',
  ReceivePerson: 'analogyx1',
  RcvDtls: [
    {
      Company: 'WOOD01',
      VendorNum: 1,
      PurPoint: '',
      PackSlip: 'qwerty',
      ReceiptDate: '2024-05-13',
      Invoiced: true,
      PONum: 26883,
      AutoReceipt: true,
      POType: 'Std',
      Received: true,
      ReceivedTo: 'PUR-STK',
      ReceivedComplete: false,
      ArrivedDate: '2024-05-13',
      VendorQty: '1',
      POLine: 2,
      PORelNum: 1,
      PartNum: 'B62',
      BinNum: 'RCV',
      EnableBin: false,
      WareHouseCode: 'Main',
      OurQty: '1',
      InputOurQty: '1',
      IUM: 'EA',
      PUM: 'EA',
      RowMod: 'A',
    },
  ],
};
