// Api to save the receipt is /Erp.BO.ReceiptSvc/UpdateMaster

export const receiptSaveJson = {
  RunChkLCAmtBeforeUpdate: true,
  RunChkHdrBeforeUpdate: true,
  ipPurPoint: '',
  ipVendorNum: 1,
  ipPackSlip: 'packslip2',
  ipPackLine: 1,
  lRunChkDtl: true,
  lRunChkDtlCompliance: false,
  lRunCheckCompliance: false,
  lRunPreUpdate: true,
  lRunCreatePartLot: true,
  partNum: '26883',
  lotNum: '',
  lOkToUpdate: false,
  ds: {
    RcvHead: [
      {
        Company: 'WOOD01',
        VendorNum: 1,
        PackSlip: 'packslip2',
        ReceiptDate: '2024-05-13',
        PONum: 26883,
        POType: 'Std',
        ArrivedDate: '2024-05-13',
        RowMod: 'A',
      },
    ],
    RcvDtl: [
      {
        Company: 'WOOD01',
        VendorNum: 1,
        PackSlip: 'packslip2',
        PackLine: 1,
        PartNum: 'B61',
        OurQty: '1',
        IUM: 'EA',
        PONum: 26883,
        POLine: 1,
        PORelNum: 1,
        ReceiptType: 'P',
        ReceivedTo: 'PUR-STK',
        POType: 'Std',
        QtyOption: 'Vendor',
        RowMod: 'A',
      },
    ],
  },
};

export const receiptWithDtls = {
  Company: 'WOOD01',
  VendorNum: 1,
  PurPoint: '',
  PackSlip: 'packslip1',
  ReceiptDate: '2024-05-21T10:35:32.617Z',
  SaveForInvoicing: true,
  Invoiced: true,
  RcvDtls: [
    {
      Company: 'WOOD01',
      VendorNum: 1,
      PurPoint: '',
      PackSlip: 'packslip2',
      PackLine: 1,
      ReceiptDate: '2024-05-13',
      Invoiced: false,
      PONum: 26883,
      AutoReceipt: false,
      POType: 'Std',
      Received: true,
      ReceivedTo: 'PUR-STK',
      ReceivedComplete: true,
      ArrivedDate: '2024-05-13',
      VendorQty: '10',
      POLine: 1,
      PORelNum: 1,
      PartNum: 'B61',
      BinNum: 'RCV',
      EnableBin: false,
      WareHouseCode: 'Main',
      JobSeqType: '',
      JobSeq: 0,
      OurQty: '1',
      InputOurQty: '1',
      IUM: 'EA',
      RowMod: 'A',
    },
  ],
};
